{% set name = "project_name" %}
{% set version = "0.2.175" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/project_name-{{ version }}.tar.gz
  sha256: 1e9c16e98afcc992fc32ba0741ec0edd5db4887f63a22e3fe44d0b8dfd0c29ef

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyquickhelper
    - python {{ python_min }}
    - setuptools <58
  run:
    - python >={{ python_min }}

test:
  imports:
    - project_name
    - project_name.subproject
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rochacbruno/python-project-template
  summary: A low dependency and simple to start project template for Python Projects.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
